name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Check Formatting
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test

  conformance:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        config:
          - name: Netty Server
            profile: netty-server
          - name: Http4s Server
            profile: http4s-server
          - name: Http4s Server (non-stable)
            profile: http4s-server-nonstable
          - name: Http4s Client
            profile: http4s-client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run conformance tests for ${{ matrix.config.name }}
        run: make test-conformance PROFILE=${{ matrix.config.profile }}

  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - uses: scalacenter/sbt-dependency-submission@v3