name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - name: Check Formatting
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test

  conformance:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        config:
          - name: Netty Server
            args: --build-arg launcher=NettyServerLauncher --build-arg config=suite-netty.yaml
          - name: Http4s Server
            args: --build-arg launcher=Http4sServerLauncher --build-arg config=suite-http4s.yaml
          - name: Http4s Server (non-stable)
            args: --build-arg launcher=Http4sServerLauncher --build-arg config=suite-http4s-nonstable.yaml --build-arg stable=false
          - name: Http4s Client
            args: --build-arg launcher=Http4sClientLauncher --build-arg config=suite-http4s-client.yaml --build-arg mode=client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run conformance tests for ${{ matrix.config.name }}
        run: docker build -f build/conformance/Dockerfile . --progress=plain ${{ matrix.config.args }}

  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - uses: scalacenter/sbt-dependency-submission@v3