name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: ./.github/actions/setup-scala

      - name: Check Formatting
        run: sbt scalafmtCheckAll

      - name: Run tests
        run: sbt test

      - name: Run conformance tests
        run: make test-conformance-stable

  dependency-graph:
    name: Update Dependency Graph
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup-scala

      - uses: scalacenter/sbt-dependency-submission@v3